openapi: 3.0.4
info:
  title: Catalog of storages log models
  description: Log models for logging services of catalog of storages
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        catalogStorage:
          $ref: '#/components/schemas/CatalogStorageLogModel'
        #        comments:
        #          $ref: '#/components/schemas/MkplLogModel'
        #        files:
        #          $ref: '#/components/schemas/MkplLogModel'
        #        images:
        #          $ref: '#/components/schemas/MkplLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CatalogStorageLogModel:
      title: Модель лога для микросервиса Catalog of storages
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/CatalogLogOperation'
        state:
          $ref: '#/components/schemas/CatalogLogState'
        requestStorage:
          $ref: '#/components/schemas/StorageLog'
        requestStorages:
          type: array
          items:
            $ref: '#/components/schemas/StorageLog'
        requestFilter:
          $ref: '#/components/schemas/StorageFilterLog'
        responseStorage:
          $ref: '#/components/schemas/StorageLog'
        responseStorages:
          type: array
          items:
            $ref: '#/components/schemas/StorageLog'

    CatalogLogState:
      type: string
      enum:
        - running
        - failed
        - finished
        -
    CatalogLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - offers
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    StorageLog:
      title: Модель лога для storage
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        capacity:
          type: string
        availability:
          type: string
        paymentType:
          type: string
        readSpeed:
          type: string
        writeSpeed:
          type: string
        enableOptimize:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    StorageFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        availability:
          type: string
        capacity:
          type: string
        paymentType:
          type: string
        readSpeed:
          type: string
        writeSpeed:
          type: string

