version: '3.9'

services:
  app-spring:
    image: my-project-app-spring:0.0.1
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "psql"
      CATALOG_STORAGES_DB_HOST: "psql"
      CATALOG_STORAGES_DB_PORT: 5432
      CATALOG_STORAGES_DB: "catalog-of-storages"
      CATALOG_STORAGES_DB_USER: "postgres"
      CATALOG_STORAGES_DB_PASS: "catalog-of-storages-pass"
      THC_PATH: "/actuator/health"
    depends_on:
      psql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/workspace/health-check"]

  psql:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: "catalog-of-storages-pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "catalog-of-storages"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: "deploy-project-migration-pg:0.0.1"
    environment:
      LIQUIBASE_URL:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://psql:5432/catalog-of-storages
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: "catalog-of-storages-pass"
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: public
    #      tableName: marketplace_ads

    depends_on:
      psql:
        condition: service_healthy
